### ISSUE TITLE
Missing twokenize_wrapper module?

### ISSUE THREAD

**Issue by andreasvlachos** [sheffieldnlp/stance-conditional#11]
I am getting the following when I run `python stancedetection/word2vec_training.py`.

If I got it right, it is needed to use this:

https://github.com/brendano/tweetmotif

But the twokenize submodule is empty. Am I missing something?

**Comment by isabelleaugenstein** [comment]
Sorry for the delayed response. See the new README. Does it work now?

**Comment by andreasvlachos** [comment]
Yes, works fine now!
