### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by andreasvlachos** [sheffieldnlp/stance-conditional#14]
After running word2vec successfully, I get the file named:

skip_nostop_single_100features_5minwords_5context

I am running:

python3 conditional.py 

But I get:

FileNotFoundError: [Errno 2] No such file or directory: '/Users/Isabelle/Documents/TextualEntailment/SemEvalStance/stance-conditional-acl2016-fresh/out/skip_nostop_single_100features_5minwords_5context_big'

I looked at the code and it seems like there is some hard coding and I am not sure which branch I should follow. Could you have a look?

**Comment by isabelleaugenstein** [comment]
Sorry, accidentally introduced that with previous commit

**Comment by andreasvlachos** [comment]
Still the same error. Is the missing file the one that is produced during wor2vec training? That one doesn't have "_big" in the end of the name.

**Comment by isabelleaugenstein** [comment]
Yes, that's the one. I'd been experimenting with two different models, which are in the Dropbox folder (https://www.dropbox.com/sh/7i2zdnet49yb1sh/AAA_AzN64JLuNlfU5pt69W8ia?dl=0)
Set  "word2vecmodel" to "small" for the "../out/skip_nostop_single_100features_5minwords_5context" model and to "big" for the "../out/skip_nostop_single_100features_5minwords_5context_big" model.

**Comment by andreasvlachos** [comment]
I see. Which one is the one used in the results of the paper? Is it the
same as the one I got when I ran word2vec training?

**Comment by isabelleaugenstein** [comment]
"big" and yes
