### ISSUE TITLE
cannot download corpus

### ISSUE THREAD

**Issue by eckolemon** [sheffieldnlp/stance-conditional#16]
we can not download the file "additionalTweetsStanceDetection.json". Why？

**Comment by isabelleaugenstein** [comment]
What do you mean by that? Do you get an error when trying to download it? The link to the folder is given in the README, i.e. https://www.dropbox.com/sh/7i2zdnet49yb1sh/AAA_AzN64JLuNlfU5pt69W8ia?dl=0, and the direct link to the file is: https://www.dropbox.com/sh/7i2zdnet49yb1sh/AAA_AzN64JLuNlfU5pt69W8ia?dl=0&preview=additionalTweetsStanceDetection.json

**Comment by eckolemon** [comment]
ok. I want to know the files in the link https://www.dropbox.com/sh/o8789zsmpvy7bu3/AABRja7NDVPtbjSa-y3GH0jAa?dl=0 are the results that have been tokenized?
