### ISSUE TITLE
Attention

### ISSUE THREAD

**Issue by rockt** [sheffieldnlp/stance-conditional#2]
Since targets and tweets are quite short attention might not have a big impact here, hence low priority.

**Comment by eckolemon** [comment]
so whether attention mechanism is necessary here？

**Comment by isabelleaugenstein** [comment]
No, it's not necessary

**Comment by eckolemon** [comment]
So why did you write attention mechanism in your paper if it is not important?

**Comment by isabelleaugenstein** [comment]
We didn't, there's no attention mechanism in our approach.
