### ISSUE TITLE
generating stance results with new dataset?

### ISSUE THREAD

**Issue by Howiezhu** [sheffieldnlp/stance-conditional#20]
I am trying to figure out what is the best way to utilize what you have and move beyond semeval-2016 datasets. I was able to follow/execute word2vec_training.py and generate the out file "skip_nostop_single_100features_5minwords_5context_big". The output file looks like a binary file and not readable.(is that just a model file?) . I am wondering how to use this code to take a list of tweets and produce a file resemble the gold_toy.txt file from eval.pl.  Ideally,I'd take a json of tweets and then get a list of AGAINST, PRO, NONE value towards target. 

This is not really an issue.

**Comment by isabelleaugenstein** [comment]
> "skip_nostop_single_100features_5minwords_5context_big". The output file looks like a binary file and not readable.(is that just a model file?)

Yes, that is a model file (the word2vec skipgram model file, to be precise)

> Ideally,I'd take a json of tweets and then get a list of AGAINST, PRO, NONE value towards target.

For this, exchange the test file with your own custom test file.
